version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/apps/ebiten-lab"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "gomod"
    directory: "/apps/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3